###############################################################################
#                               IMPORTANT NOTICE                                #
###############################################################################
#                                                                             #
# This file was generated by Terraform.                                       #
# Please do not edit this file directly.                                      #
# Instead, edit the vault_secret module in terraform code and re-run it       #
# to update this file.                                                        #
#                                                                             #
###############################################################################

name: 'Get Vault Secrets'
description: 'Retrieve secrets from HashiCorp Vault'

inputs:
  vault_addr:
    description: 'Vault server address'
    required: true
  droplet_ip:
    description: 'Droplet IP address'
    required: true
  ssh_private_key:
    description: 'SSH private key for server access'
    required: true
  secret_path:
    description: 'Path to secret in Vault'
    required: true
    default: 'secret/data/config'

outputs:
%{ for output in outputs ~}
  ${output["name"]}:
    description: '${output["description"]}'
    value: $${{ steps.vault.outputs.${output["name"]} }}
%{ endfor ~}

runs:
  using: "composite"
  steps:
    - name: Generate Action Outputs
      id: vault
      shell: bash
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $${{ inputs.droplet_ip }} >> ~/.ssh/known_hosts

        # Get vault token and data using vault CLI
        VAULT_DATA=$(ssh -i ~/.ssh/id_rsa deployuser@$${{ inputs.droplet_ip }} '
          ROOT_TOKEN=$(grep "Initial Root Token:" /home/deployuser/.vault/vault_credentials.txt | cut -d" " -f4)
          VAULT_CONTAINER=$(docker ps -q -f name=vault)
          docker exec $VAULT_CONTAINER sh -c "VAULT_TOKEN=$ROOT_TOKEN vault kv get -format=json secret/config" | jq -r ".data.data"
        ')

        # Clean up SSH key
        rm -f ~/.ssh/id_rsa

        # Export raw data for debugging
        echo "raw_vault_data<<EOF" >> "$GITHUB_OUTPUT"
        echo "$VAULT_DATA" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

        # Export each key-value pair directly to GITHUB_OUTPUT
        echo "$VAULT_DATA" | jq -r 'to_entries | .[] | .key + "=" + (.value | tostring)' | while read -r line; do
          # If the value contains newlines or special characters, use the EOF syntax
          if [[ "$line" == *$'\n'* ]] || [[ "$line" == *'"'* ]] || [[ "$line" == *'['* ]]; then
            key="$${line%%=*}"
            value="$${line#*=}"
            echo "$${key}<<EOF" >> "$GITHUB_OUTPUT"
            echo "$${value}" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "$line" >> "$GITHUB_OUTPUT"
          fi
          key=$(echo "$line" | cut -d'=' -f1)
          echo "Exported: $key=***"
        done


