source 'https://rubygems.org'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0"

gem 'stringio', '~> 3.1.2'

# Authentication
gem 'devise', '~> 4.8'
gem 'devise-jwt', '~> 0.11.0'

# GraphQL
gem 'graphql', '~> 2.3', '>= 2.3.2'
gem 'graphql-batch', '~> 0.5.3'
gem 'apollo_upload_server', '~> 2.1'

# Email
gem 'postmark-rails', '~> 0.22.1'

# Utility
gem 'bootsnap', require: false # Reduces boot times through caching
gem 'tzinfo-data', platforms: %i[windows jruby] # Windows time zone data

# Asset Pipeline
gem 'propshaft', '~> 0.9.0', group: :development

# CORS
gem 'rack-cors', '~> 2.0', '>= 2.0.2'

# Mongoid is an ODM (Object-Document Mapper) for MongoDB, similar to how ActiveRecord is an ORM for SQL databases.
# It provides a high-level abstraction for interacting with MongoDB using Rails models.
gem 'mongoid', '~> 9.0'

# Production Gems
group :production do
  gem 'puma', '>= 5.0'
  # The mongo gem is the official MongoDB Ruby driver that provides low-level access to MongoDB.
  # It is used by Mongoid to perform the actual communication with the MongoDB server.
  gem 'mongo', '~> 2.20'
end

# Development and Test Gems
group :development, :test do
  gem 'database_cleaner-mongoid'
  gem 'debug', platforms: %i[mri windows] # Debugging tools
  gem 'dotenv-rails', '~> 3.1', '>= 3.1.2'
  gem 'factory_bot_rails', '~> 6.4', '>= 6.4.3'
  gem 'faker', '~> 3.4', '>= 3.4.1'
  gem 'graphiql-rails', '~> 1.7'
  gem 'rspec-rails', '~> 6.1', '>= 6.1.2'

  gem 'simplecov', '~> 0.22.0', require: false

  # Add WebMock for testing HTTP requests
  gem 'webmock'

  # Add Guard and Guard-RSpec for automatically running tests
  gem 'guard', '~> 2.18'
  gem 'guard-rspec', '~> 4.7'
end

# Add HTTParty for making HTTP requests
gem 'httparty'
gem 'vault', '~> 0.18.0'

group :development do
  gem 'rubocop', '~> 1.64', '>= 1.64.1'
  gem 'rubocop-rails', '~> 2.25'
  gem 'letter_opener_web', '~> 3.0'
end
